"""
URL configuration for lenskart project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from lensapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/',views.mytest),
    path('demo/',views.demopage),
    path('2_premium/',views.premium),
    path('form/',views.form),
    path('formcode/',views.formcode),
    path('show/',views.show),
    path('delete/<int:id>',views.delete),
    path('form2/',views.form),
    path('form2code/',views.formcode),
    path('delete/<int:id>',views.delete),
    path('abc/',views.abc),
    path('abccode/',views.abccode),
    path('show2/',views.show2),
    path('delete/<int:id>',views.delete),
    path('edit/<int:id>',views.edit),
    path('update/',views.update),
    path('signup/',views.signup),
    path('signupcode/',views.signupcode),
    path('login/',views.login),
    path('logincode/',views.logincode),
    path('dashboard/',views.dashboard),
    path('changepassword/',views.changepassword),
    path('changepasscode/',views.changepasscode),
    path('logout/',views.logout),
    path('form3/',views.form3),
    path('form3code/',views.form3code),
    path('step1/',views.step1),
    path('step2/',views.step2),
    path('step3/',views.step3),
    path('step1code/',views.step1code),
    path('step2code/',views.step2code),
    path('step3code/',views.step3code),
    path('img/',views.img),
    path('imgcode/',views.imgcode),
    path('imgshow/',views.imgshow),
    path('img1/',views.img1),
    path('img1code/',views.img1code),
    path('img1show/',views.img1show),
    path('delete/<int:id>',views.delete),
    path('forgetpass/',views.forgetpass),
    path('forgetpasscode/',views.forgetpasscode),
    path('otppage/',views.otppage),
    path('otpcode/',views.otpcode),
    path('resetpass/',views.resetpass),
    path('resetpasscode/',views.resetpasscode),
    path('',views.head2),
    path('head2code/',views.head2code),
    path('signincode/',views.signincode),
    path('trackcode/', views.trackcode),
    path('do_more_be_more2/',views.do_more_be_more2),
    path('john_jacobs_nav/',views.john_jacobs_nav),
    path('aqua_lens/',views.aqua_lens),
    path('singapore2/',views.singapore2),
    path('nav_eyeglass/<int:id>',views.nav_eyeglass),
    path('cat_eye/<int:id>', views.cat_eye),
    path('nav_sunglass/<int:id>', views.nav_sunglass),
    path('nav_computer/',views.nav_computer),
    path('nav_kids/',views.nav_kids),
    path('nav_contact/',views.nav_contact),
    path('nav_sunglass/',views.nav_sunglass),
    path('blu_button/',views.blu_button),
    path('progressive_lens/',views.progressive_lens),
    path('john_jacobs/',views.john_jacobs),
    path('vinchent_chase/',views.vinchent_chase),
    path('rounds/<int:id>',views.rounds),
    path('transparent/',views.transparent),
    path('mouni_roy/',views.mouni_roy),
    path('karan_johar/',views.karan_johar),
    path('buying_guide/',views.buying_guide),
    path('size_guide/',views.size_guide),
    path('FAQs/',views.FAQs),
    path('contact_nine/',views.contact_nine),
    path('John_Jacobs_Card1/<int:id>',views.John_Jacobs_Card1),
    path('nav_sunglass_card1/<int:id>',views.nav_sunglass_card1),
    path('John_jacobs_Card2/',views.John_jacobs_Card2),
    path('John_Jacobs_Card3/', views.John_Jacobs_Card3),
    path('John_jacobs_card4/', views.John_jacobs_card4),
    path('John_Jacobs_Card5/', views.John_Jacobs_Card5),
    path('John_Jacobs_Card6/', views.John_Jacobs_Card6),
    path('buy_step2/<int:id>',views.buy_step2),
    path('buy_step2_part2/<int:id>',views.buy_step2_part2),
    path('buy_step2_part3/<int:id>', views.buy_step2_part3),
    path('buy_step2_part6/<int:id>', views.buy_step2_part6),
    path('buy_step_3/',views.buy_step_3),
    path('buy_step_3part1/', views.buy_step_3part1),
    path('buy_step_4/<int:id>',views.buy_step_4),
    path('buy_step_5/', views.buy_step_5),
    path('summary/',views.summary),
    path('full_rim/',views.full_rim),
    path('Buy_step1/<int:id>',views.Buy_step1),
    path('round_card1/<int:id>', views.round_card1),
    path('card2_Buy/',views.card2_Buy),
    path('card3_Buy_step_1/',views.card3_Buy_step_1),
    path('card4_Buy_step_1/', views.card4_Buy_step_1),
    path('card5_Buy_step_1/', views.card5_Buy_step_1),
    path('card6_Buy_step_1/', views.card6_Buy_step_1),
    path('nav_sunglass_card1/',views.nav_sunglass_card1),
    path('nav_sunglass_card2/',views.nav_sunglass_card2),
    path('nav_sunglass_card3/', views.nav_sunglass_card3),
    path('nav_sunglass_card4/', views.nav_sunglass_card4),
    path('nav_sunglass_card5/', views.nav_sunglass_card5),
    path('nav_sunglass_card6/', views.nav_sunglass_card6),
    path('nav_contact_card1/',views.nav_contact_card1),
    path('nav_contact_card2/',views.nav_contact_card2),
    path('nav_contact_card3/',views.nav_contact_card3),
    path('nav_contact_card4/',views.nav_contact_card4),
    path('nav_contact_card5/',views.nav_contact_card5),
    path('nav_contact_card6/',views.nav_contact_card6),
    path('comp_card1/',views.comp_card1),
    path('comp_card2/',views.comp_card2),
    path('comp_card3/',views.comp_card3),
    path('comp_card4/',views.comp_card4),
    path('comp_card5/',views.comp_card5),
    path('comp_card6/',views.comp_card6),
    path('nav_contact_card1/',views.nav_contact_card1),
    path('nav_contact_card2/',views.nav_contact_card2),
    path('nav_contact_card3/',views.nav_contact_card3),
    path('nav_contact_card4/',views.nav_contact_card4),
    path('nav_contact_card5/',views.nav_contact_card5),
    path('nav_contact_card6/',views.nav_contact_card6),
    path('Vincent_Chase_card1/',views.Vincent_Chase_card1),
    path('Vncent_Chase_Card2/',views.Vncent_Chase_Card2),
    path('Vincent_Chase_card3/',views.Vincent_Chase_card3),
    path('Vincent_Chase_Card4/',views.Vincent_Chase_Card4),
    path('Vincent_Chase_Card5/',views.Vincent_Chase_Card5),
    path('Vincent_Chase_Card6/',views.Vincent_Chase_Card6),
    path('karan_johar_card1/',views.karan_johar_card1),
    path('karan_johar_card2/', views.karan_johar_card2),
    path('karan_johar_card3/', views.karan_johar_card3),
    path('karan_johar_card4/', views.karan_johar_card4),
    path('karan_johar_card5/', views.karan_johar_card5),
    path('karan_johar_card6/', views.karan_johar_card6),
    path('cat_eye_card1/',views.cat_eye_card1),
    path('cat_eye_card2/',views.cat_eye_card2),
    path('cat_eye_card3/',views.cat_eye_card3),
    path('cat_Eye_card4/',views.cat_Eye_card4),
    path('cat_eye_card5/',views.cat_eye_card5),
    path('cat_Eye_card6/',views.cat_Eye_card6),
    path('mouni_roy_card1/',views.mouni_roy_card1),
    path('mouni_roy_card2/',views.mouni_roy_card2),
    path('mouni_roy_card3/',views.mouni_roy_card3),
    path('mouni_roy_card4/',views.mouni_roy_card4),
    path('mouni_roy_card5/',views.mouni_roy_card5),
    path('mouni_roy_card6/',views.mouni_roy_card6),
    path('kids_card1/',views.kids_card1),
    path('kids_card2/',views.kids_card2),
    path('kids_card3/',views.kids_card3),
    path('kids_card4/',views.kids_card4),
    path('kids_card5/',views.kids_card5),
    path('kids_card6/',views.kids_card6),
    path('round_card1/<int:id>',views.round_card1),
    path('round_card2/',views.round_card2),
    path('round_card3/',views.round_card3),
    path('round_card4/',views.round_card4),
    path('round_card5/',views.round_card5),
    path('round_card6/',views.round_card6),
    path('transparent_card1/',views.transparent_card1),
    path('transparent_card2/',views.transparent_card2),
    path('transparent_card3/',views.transparent_card3),
    path('transparent_card4/',views.transparent_card4),
    path('transparent_card5/',views.transparent_card5),
    path('transparent_card6/',views.transparent_card6),
    path('nine_nine_card1/',views.nine_nine_card1),
    path('nine_nine_card2/', views.nine_nine_card2),
    path('nine_nine_card3/', views.nine_nine_card3),
    path('nine_nine_card4/', views.nine_nine_card4),
    path('nine_nine_card5/', views.nine_nine_card5),
    path('nine_nine_card6/', views.nine_nine_card6),
    # path('cart/',views.cart),
    path('signin_page3/<int:id>',views.signin_page3),
    path('my_order/',views.my_order),
    path('account_info/<int:id>',views.account_info),
    path('review_rating/',views.review_rating),
    path('reviewcode/',views.reviewcode),
    # path('wishlist/',views.wishlist),
    path('Admin_Panel/delete_product/',views.delete_product),

    path('Admin_Panel/admin/',views.admin),
    path('Admin_Panel/add_category/', views.add_category),
    path('Admin_Panel/add_category3/', views.add_category3),
    path('Admin_Panel/add_pageone/', views.add_pageone),
    path('Admin_Panel/categorycode/', views.categorycode),
    path('Admin_Panel/pageonecode/', views.pageonecode),
    path('Admin_Panel/addcategory3/', views.addcategory3),
    path('Admin_Panel/auth_logout/',views.auth_logout),
    path('Admin_Panel/ecommerce_add_product/',views.ecommerce_add_product),
    path('Admin_Panel/addproductcode/',views.addproductcode),
    path('Admin_Panel/add_product_pageone/', views.add_product_pageone),
    path('Admin_Panel/add_product3/', views.add_product3),
    path('Admin_Panel/addproductpageonecode/', views.addproductpageonecode),
    path('Admin_Panel/addproductcode3/', views.addproductcode3),
    path('Admin_Panel/ecommerce_customers/', views.ecommerce_customers),
    path('Admin_Panel/customercode/', views.ecommerce_customers),
    path('Admin_Panel/ecommerce_orders/',views.ecommerce_orders),
    path('Admin_Panel/show_category/',views.show_category),
    path('Admin_Panel/rating/',views.rating),
    path('Admin_Panel/order_status/',views.order_status),
    path('Admin_Panel/show_category3/',views.show_category3),
    path('Admin_Panel/show_pageone/',views.show_pageone),
    path('Admin_Panel/show_product_pageone/',views.show_product_pageone),
    path('Admin_Panel/show_product3/',views.show_product3),
    path('Admin_Panel/page_banners/',views.page_banners),
    path('Admin_Panel/imagecode/',views.imagecode),
    path('Admin_Panel/add_category2/',views.add_category2),
    path('Admin_Panel/show_category2/',views.show_category2),
    path('Admin_Panel/categorycode2/', views.categorycode2),
    path('Admin_Panel/add_product2/',views.add_product2),
    path('Admin_Panel/addproductcode2/', views.addproductcode2),
    path('Admin_Panel/show_product2/',views.show_product2),
    path('Admin_Panel/buy_product/',views.buy_product),
    path('Admin_Panel/show_step1/',views.show_step1),
    path('Admin_Panel/buyproductcode/',views.buyproductcode),
    path('Admin_Panel/buy_product2/',views.buy_product2),
    path('Admin_Panel/buy_product3/', views.buy_product3),
    path('Admin_Panel/buy_product4/', views.buy_product4),
    path('Admin_Panel/show_step2/',views.show_step2),
    path('Admin_Panel/show_step3/',views.show_step3),
    path('Admin_Panel/show_step4/', views.show_step4),
    path('Admin_Panel/buyproductcode2/',views.buyproductcode2),
    path('Admin_Panel/buyproductcode3/', views.buyproductcode3),
    path('Admin_Panel/buyproductcode4/', views.buyproductcode4),
    path('Admin_Panel/front/',views.front),
    path('Admin_Panel/frontcode/',views.frontcode),
    path('Admin_Panel/frontshow/',views.frontshow),
    path('account_info/',views.account_info),
    path('Admin_Panel/registration_show/',views.registration_show),
    path('Admin_Panel/add_registration/',views.add_registration),
    path('Admin_Panel/registrationcode/',views.registrationcode),
    path('accountcode/',views.accountcode),
    path('ratingcode/',views.ratingcode),
    path('ratingcode1/',views.ratingcode1),
    path('ratingcode2/', views.ratingcode2),
    path('Admin_Panel/edit_registration/',views.edit_registration),
    path('Admin_Panel/show_edit_registration/',views.show_edit_registration),
    path('account_info/',views.editcode),
    path('cart/<int:id>',views.cart),
    path('cart1/<int:id>',views.cart1),
    path('cart3/<int:id>', views.cart3),
    path('cart4/<int:id>', views.cart4),
    path('wishlist/<int:id>',views.wishlist),
    path('wishlist1/<int:id>',views.wishlist1),
    path('wishlist3/<int:id>',views.wishlist3),
    path('wishlist4/<int:id>',views.wishlist4),
    path('wishlist_show/',views.wishlist_show),
    path('wishlist1_show/',views.wishlist1_show),
    path('wishlist3_show/', views.wishlist3_show),
    path('wishlist4_show/', views.wishlist4_show),
    path('cart_show/',views.cart_show),
    path('cart1_show/', views.cart1_show),
    path('cart3_show/', views.cart3_show),
    path('cart4_show/', views.cart4_show),
    path('deletecode/<int:pid>', views.deletecode),
    path('deletecode1/<int:pid>', views.deletecode1),
    path('deletecode3/<int:pid>', views.deletecode3),
    path('deletecode4/<int:pid>', views.deletecode4),
    path('cartt/',views.cartt),
    path('Admin_Panel/navbar/',views.navbar),
    path('Admin_Panel/navbarcode/', views.navbarcode),
    path('Admin_Panel/navbar_show/',views.navbar_show),
    path('deletecodee/<int:pid>', views.deletecodee),
    path('deletecodee1/<int:pid>', views.deletecodee1),
    path('deletecodee5/<int:pid>', views.deletecodee5),
    path('deletecodee6/<int:pid>', views.deletecodee6),
    path('shippingcode/',views.shippingcode),
    path('Razorpay/<int:id>',views.index1),
    path('Admin_Panel/shipping_data/',views.shipping_data),
    path('order_tracking/',views.order_tracking),
    path('Admin_Panel/invoice_bill/<int:id>',views.invoice_bill),
    path('Admin_Panel/shipping1/<int:id>',views.shipping1),
    path('Admin_Panel/updateshipdata/',views.updateshipdata),
    path('track_order/<int:id>',views.track_order),
    path('tryon/', views.tryon),
    path('order_data_show/',views.order_data_show),
    path('Admin_Panel/categorydelete/<int:id>',views.categorydelete),
    path('Admin_Panel/ratingdelete/<int:id>',views.ratingdelete),
    path('Admin_Panel/category_edit/<int:id>',views.category_edit),
    path('Admin_Panel/cateditcode/',views.cateditcode),
    #path('search/',views.search),









]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
